language: node_js
node_js:
  - 0.10
  
addons:
  firefox: "36.0.1"

env: BROWSERS=Chrome E2E_BROWSERS=Chrome

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run update-webdriver

script:
  - scripts/private/test-all.sh
